openai_key:  "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"
notion_token: "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"
notion_db:    "1e36f8c3d71c80a3b1afc094553e5b1e"
reddit_client: "YOUR_REDDIT_CLIENTID"
reddit_secret: "YOUR_REDDIT_SECRET"
