openai_key:  "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"
notion_token: "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"
notion_db:    "1e36f8c3d71c80a3b1afc094553e5b1e"
reddit_client: "h2NERXlQ4_T7PJko8XkAeQ"
reddit_secret: "ptz9MDKTfejySVYpCfwUZ1_6JHxnew"
