openai_key:  "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"
notion_token: "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"
notion_db:    "1e36f8c3d71c80a3b1afc094553e5b1e"
reddit_client: "h2NERXlQ4_T7PJko8XkAeQ"
reddit_secret: "ptz9MDKTfejySVYpCfwUZ1_6JHxnew"
